### ISSUE TITLE
Rangepicker should not initialize itself to week.

### ISSUE THREAD

**Issue by lrbridge** [PredixDev/px-rangepicker#1]
This seems to be causing a lot of race conditions and confusion.  @carlosfhernandez @mdwragg

**Comment by nonmetalhail** [comment]
@carlosfhernandez This is a feature request. Can you please prioritize this?

**Comment by benoitjchevalier** [comment]
Not sure if this is still an issue with the major rework rangepicker has had. I'm going to close this for now, please reopen if you feel this is still an issue.
