### ISSUE TITLE
Modal position is broken inside px-card

### ISSUE THREAD

**Issue by KevinVecchione** [PredixDev/px-rangepicker#11]
Modal appears behind date range fields when used inside px-card. 

Usage:
````
<link rel="import" href="../bower_components/px-rangepicker/px-rangepicker.html"/>

<dom-module id="time-series-data">
    <template>
        <px-card header-text='Time Series Data'>
            <px-rangepicker></px-rangepicker>
        </px-card>
    </template>
</dom-module>

<script>
    Polymer({
        is: 'time-series-data',
        behaviors: [px.card]
    });
</script>
````

Result:
![image](https://cloud.githubusercontent.com/assets/915510/15681890/226dcdba-2729-11e6-8f2f-32a09cf30fa2.png)

**Comment by benoitjchevalier** [comment]
Not sure if this is still an issue with the major rework rangepicker has had. I'm going to close this for now, please reopen if you feel this is still an issue.
