### ISSUE TITLE
Should "Block past dates" flag keyed on "From" date?

### ISSUE THREAD

**Issue by kwge** [PredixDev/px-rangepicker#13]
Right now, enabling "Block pass dates" flag will disable all dates before today.  In our use case, we want to enable a range of days, and disable all remaining dates.  It will be nice to have both "Block past dates" and "Block Future datas" set, and "Block pass dates" is keyed on the "From" date field and "Block future dates" is keyed on "To" date field.  So only the days within "From" date field and "To" date field are selectable.

**Comment by benoitjchevalier** [comment]
"Block past date" and "Block future dates" both aim at being features based on "Today". 

This would need to be implemented as an additional feature. Px-calendar-picker already uses such a feature internally (blockDatesBefore and blockDatesAfter), so they would need to be:
-Propagated to px-range-panel and px-rangepicker
-Implemented in validation, then propagated to px-datetime-entry, px-datetime-field and px-datetime-range-field

By propagated I mean they only need to be bound to the child element in the HTML, validation would handle all the logic.

If you're willing to try implementing it I'm more than happy to review the appropriate Pull Requests and answer your questions

**Comment by benoitjchevalier** [comment]
Someone else requested a similar feature today (having the ability to block a specific before/after date)

**Comment by harini2016** [comment]
@benoitjchevalier I was also about to request similar feature on this component. I had a similar usecase too.

**Comment by benoitjchevalier** [comment]
This feature will be worked on in the near future

**Comment by niveditach** [comment]
Is there a way I can block future time also for the current date?

**Comment by benoitjchevalier** [comment]
We'll consider it during the implementation of this feature

**Comment by randyaskin** [comment]
I have added the `min` and `max` properties to all of the datetime components - fields will show validation errors and calendars will disable the date buttons for dates outside of the specified range. @niveditach I also turned off the rounding logic on the definition of "future" and "past" as @Menkhaus-ge couldn't remember why we had it there - though of course users will now have to remember to account for the timezone property.
