### ISSUE TITLE
Time zone drop down is too narrow to use

### ISSUE THREAD

**Issue by randyaskin** [PredixDev/px-rangepicker#16]
## Expected behavior and actual behavior:

I would expect that the time zone dropdown would be wide enough to actually read the values in order to pick one. As it is, the dropdown is so narrow in some situations that you can't read anything past "GMT" meaning you have no idea which timezone you're picking.
## Screenshots:

![time zone](https://cloud.githubusercontent.com/assets/2130613/17897266/687a353e-6908-11e6-80eb-18e57515d2e7.png)

**Comment by benoitjchevalier** [comment]
At the moment the dropdown value displayed automatically resize, and the dropdown content is this size + X. When the displayed value is too small we end up in that case where content can't be read.

Maybe we should add a property allowing the content to adjust its width automatically based on what's inside? Happy to hear about design suggestions

**Comment by randyaskin** [comment]
Yeah, I figured it was based on the display value, and likely a quirk of px-dropdown rather than px-rangepicker specifically. I would think we would do width auto, based on the contents, but maybe specify a max width so it doesn't run off the screen or something.

**Comment by randyaskin** [comment]
Closing, as this is more an issue with dropdown than rangepicker.
