### ISSUE TITLE
"Invalid Date" error

### ISSUE THREAD

**Issue by tiffeli** [PredixDev/px-rangepicker#17]
I'm on the APM analytics team and I have an issue using px-datetime-picker.

The object I pass into range does not render the dates correctly, I get the error of "invalid date range". 

my range object is populated like so (and I've tried without the JSON.stringify) : 

```
 $scope.rangeDate = JSON.stringify({
        "from": moment().toISOString(),
        "to": moment().toISOString()
    });
```
So it looks like :
```
{from: "2016-08-25T23:09:38.031Z", to: "2016-08-25T23:09:38.031Z"}
```

and the example object given in the demo is:
```
{"from":"2016-01-01T00:00:00.000Z","to":"2016-07-01T11:00:00.000Z"}
```

how can I get the dates to render without hard coding it. 
Note: I've gotten this to work in a React app but not an Angular app.

**Comment by benoitjchevalier** [comment]
Hello,

Let me try to clarify. I'm assuming you're using px-rangepicker and not px-datetime-picker?

a few point you can try:

- make sure you set the "range" property of the range picker (as opposed to rangeDate)

- Set the "range" property with an object, not a string (so no JSON.stringify was right)

- Try having "to" a bit later than "from". One second can be enough, you can try one day if that doesn't work. ( => moment().add(1, 'seconds').toISOString() or moment().add(1, 'days').toISOString() )

Let me know if you're still stuck!

Cheers,
Ben

**Comment by tiffeli** [comment]
Hi,
My apologies! I meant px-datetime-picker. 

I was using the 'range' property. I just called the object that I passed into range="<rangeDate>". 

I have tried it without stringifying it, and made sure the type was an object by checking typeof.

I originally did 'from' yesterday (```moment().subtract(1, 'day').toISOString()```) 'to' currently. And that didn't work either. 

This is what I'm currently trying: 
```
const yesterday = moment().subtract(1, 'day').toISOString()

 $scope.range = {
        "from": yesterday,
        "to": moment().toISOString()
    };
```
```
<px-rangepicker range='range' date-format="YYYY/MM/DD" time-format="hh:mm:ss A" show-buttons="true" show-time-zone="text" time-zone="UTC"></px-rangepicker>
```

**Comment by tiffeli** [comment]
Hi.

Apologies, I did mean rangepicker. 

-I was setting the "range" property. "rangeDate" is just what I named the object I passed into "range".
- I tried it without stringifying it (also checked that the type was an object) 
-originally, I tried it from yesterday to currently. 

Here's what I have now (not working either) : 
```
    const yesterday = moment().subtract(1, 'day').toISOString();
    $scope.range = {
        "from": yesterday,
        "to": moment().toISOString()
    };

```
```
<px-daterange-rangepicker range="range" date-format="YYYY/MM/DD" time-format="hh:mm:ss A" show-buttons="true" show-time-zone="text" time-zone="UTC"></px-rangepicker>
```

**Comment by benoitjchevalier** [comment]
Hello,

thanks for the clarification.

It looks like you're passing the litteral "range" string to the range property in the px-rangepicker HTML, which is invalid.

I'm not sure what $scope is in that context, is it a reference to the rangepicker or something else? 

You'll either need to :

- databind a range object in the HTML: `<px-daterange-rangepicker range="{{yourRangeObject}}" date-format="YYYY/MM/DD" time-format="hh:mm:ss A" show-buttons="true" show-time-zone="text" time-zone="UTC"></px-rangepicker>`
- OR set the range property in javascript: `document.getElementById('yourRangepicker').range = {
        "from":moment().subtract(1, 'day').toISOString(),
        "to": moment().toISOString()
    };`

Let me know if that helps.

Cheers,
Ben

**Comment by tiffeli** [comment]
Hi,

Thanks for the follow up! The problem was exactly that. I was able to solve it using the first method. 

```
<px-rangepicker id="the-range-picker" is-utc range="{{range}}"></px-rangepicker>
```
 Thank you!
