### ISSUE TITLE
Open calendar in the centre of the screen or position itself in the visible screen 

### ISSUE THREAD

**Issue by srk289** [PredixDev/px-rangepicker#18]
If the range picker is positioned on the right corner of the screen, the calendar dialog doesn't place itself accordingly. Is there a easy way to just make the calendar open either in a modal which is placed in the centre of the screen or can the dialog position itself in the visible screen automatically?

**Comment by benoitjchevalier** [comment]
Thanks for the feedback, this sounds like a bug to me, we should fix it so that the dialog  smartly position itself when the rangepicker is close to a border

**Comment by randyaskin** [comment]
v3 of the rangepicker now uses iron-dropdown for more intelligent dynamic positioning of the panel. Please let us know if this does not meet your requirements.
