### ISSUE TITLE
Allow ability to trigger daterange dialog from Light DOM

### ISSUE THREAD

**Issue by srk289** [PredixDev/px-rangepicker#19]
It would be great to trigger date range dialog from Light DOM. 
For example: Clicking on the button triggers the rangepicker dialog to open

```
<px-rangepicker date-format="DD/MM/YYYY" time-format="hh:mm" ... >
 <button class="trigger btn">Open rangepicker</button>
</px-rangepicker>
```

**Comment by Menkhaus-ge** [comment]
Thanks for your feedback, we'll have to prioritize and investigate this added functionality

**Comment by katemenkhaus** [comment]
This is possible by using px-datetime-range-panel only. You can add your own trigger to open the panel.  The purpose of rangepicker is to combine `px-datetime-range-field` and `px-datetime-range-panel`.
