### ISSUE TITLE
Support configuring a maximum range

### ISSUE THREAD

**Issue by manderson23** [PredixDev/px-rangepicker#20]
It would be useful if the range picker supported specifying a maximum range.

If could either block the user from picker a range > the maximum or show a validation error.

**Comment by sebastianroming** [comment]
Any updates on this? :+1: :fire:

**Comment by randyaskin** [comment]
Nope, we've been fully allocated on providing a design refresh of the entire system, haven't had time to focus on any additional requests this quarter. Goal is to finish that up 7/28 and move on to other things then.

**Comment by sebastianroming** [comment]
@randyaskin design refresh done ... is there any roadmap when (and if...?) this feature will be implemented? 
This is really an important feature and a k.o. criteria for px-rangepicker in our ecosystem... 

Would be awesome to see this feature soon :+1:

**Comment by randyaskin** [comment]
In progress - https://github.com/PredixDev/px-datetime-common/pull/14

**Comment by randyaskin** [comment]
The `min` and `max` properties have been added throughout all of the datetime components, including rangepicker.
