### ISSUE TITLE
is localization supported for this component

### ISSUE THREAD

**Issue by niveditach** [PredixDev/px-rangepicker#25]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
Localization is a broad term, can you be more specific? As shown on the [demo/API page](https://www.predix-ui.com/#/components/px-rangepicker/), you can supply a custom date format, and it supports various time zone options. It does not currently support automatic geolocation detection or translation of month names, for instance. What other l10n options are you looking for?

**Comment by niveditach** [comment]
I was looking at the 'TO' text between the start and enddate, so was asking.

**Comment by randyaskin** [comment]
Ah yes, that's on our list to localize whenever we get around to it - along with "Apply" "Cancel" "Presets" month names, days of the week, etc.

**Comment by niveditach** [comment]
Thanks Randy

**Comment by randyaskin** [comment]
Localization was added in v1.4.0 of this component. Currently investigating why the API page isn't rebuilding, and we will also be releasing some documentation on predix.io around how to best set up localization for your application, but feel free to poke around in the code in the meantime.
