### ISSUE TITLE
On selecting the same From and To dates on the filter it displays a wrong message to the user

### ISSUE THREAD

**Issue by surekhakolekar** [PredixDev/px-rangepicker#28]
Steps to Reproduce:-
1.Select the Same From and To Date

Actual-
It displays an error message ' From date cannot be later than TO Date'

Expected-
There should not be any error message.

Screenshot:
![same date error](https://cloud.githubusercontent.com/assets/1745071/22886281/198b9d2e-f223-11e6-9940-3d46f13fe77b.jpg)

**Comment by nonmetalhail** [comment]
Assigning the same exact time and date is an error as the rangepicker cannot have the same time assigned to both `To` and `From`. It must be a valid range where the `From` is greater than the `To`. 

If you want a single date, use the [datetime picker](https://www.predix-ui.com/#/components/px-datetime-picker/) instead.
