### ISSUE TITLE
Previous months and years on TO Date are disabled when selecting FROM Date via calendar

### ISSUE THREAD

**Issue by reimonpangan** [PredixDev/px-rangepicker#30]
Hi,

Encountered this issue where I select a date in the FROM calendar via clicking, the TO date from the previous months is disabled

Steps to reproduce the problem:
1.	Click on the header of the FROM date to reduce the selection. Ex. DEC 25 2014
![image](https://cloud.githubusercontent.com/assets/27317144/24935469/e281e3d8-1f54-11e7-8ef0-9d91febfce34.png)

![image](https://cloud.githubusercontent.com/assets/27317144/24935485/feb35ce4-1f54-11e7-84aa-67754dc87d3d.png)

![image](https://cloud.githubusercontent.com/assets/27317144/24935486/02bf21c4-1f55-11e7-8011-282316a80a22.png)

![image](https://cloud.githubusercontent.com/assets/27317144/24935488/07136460-1f55-11e7-8a71-e1b0d9b90b16.png)

![image](https://cloud.githubusercontent.com/assets/27317144/24935491/0a430c26-1f55-11e7-8ba3-87b990e63fb7.png)

![image](https://cloud.githubusercontent.com/assets/27317144/24935496/0dbc0c40-1f55-11e7-96a2-2f5d111c5b4a.png)

2.	In the TO date, select a date in MARCH 2017 using the directional button “<”

![image](https://cloud.githubusercontent.com/assets/27317144/24935513/24054d86-1f55-11e7-9fec-63b64f9ef7b1.png)

![image](https://cloud.githubusercontent.com/assets/27317144/24935597/887ff6d0-1f55-11e7-92a0-0d836d1e22fb.png)

![image](https://cloud.githubusercontent.com/assets/27317144/24935619/970afd8a-1f55-11e7-9977-0cf04a4079b9.png)

![image](https://cloud.githubusercontent.com/assets/27317144/24935623/9d55f690-1f55-11e7-8372-1561548e52d2.png)

Environment: bower v1.3.10, CHrome and Firefox running on Windows 10

Thanks!

**Comment by katemenkhaus** [comment]
Cannot reproduce in the latest version v3.3.2
Reopen if you are still having this issue.
