### ISSUE TITLE
Access range in angular2 component?

### ISSUE THREAD

**Issue by dgt009** [PredixDev/px-rangepicker#31]
## Expected behavior and actual behavior:
I have two predix polymer component
1) px-rangepicker
2) px-simple-horizontal-bar-chart

and I want to select the date range and accordingly the chart should change.
how can I pass the selected daterange from html to component ?
do we have any example or demo for this ?

## Steps to reproduce the problem:
```
<!--Component.html-->
<div>
<px-rangepicker 
        show-buttons="true" 
        date-format="YYYY/MM/DD" 
        time-format="HH:mm:ss" 
        time-zone="UTC" 
        show-time-zone="abbreviatedText" 
        [range]="range"
        px-datetime-range-submitted = 'onDateTimeSelect(range)'
        >
</px-rangepicker>

</div>

<px-simple-horizontal-bar-chart 
        width="550" 
        height="200" 
        bar-labels="percentage" 
        legend-labels='["Apples","Oranges","Peaches"]' 
        chart-data='[2,8,5]'>

</px-simple-horizontal-bar-chart>
```

```
//component.ts
public range = {
   "from": "2013-01-07T22:44:30.652Z",
   "to" : "2013-02-04T22:44:30.652Z"
};
public onDateTimeSelect(datetime){
    console.log(datetime);
  }
```
## Environment 
Browser : Chrome
Angular2

**Comment by MuriloEduardo** [comment]
If you use ngModel in your HTML element and in your component using "this.mymodel" does not solve?

**Comment by dgt009** [comment]
@MuriloEduardo 
It's a customized html element, I don't think it would work that way unless the element is configured to use ngModel.
could you show me an example where I could access the range in component method onClick Submit button.?

**Comment by MuriloEduardo** [comment]
@dgt009

You need to use the `@Input` decorator, you will create attribute with proprety binding and its component must be declared this attribute with any public variable.

Read about the `@Input` and `@Output` decorators

**Comment by mdwragg** [comment]
Sounds like y'all helped each other out. Thank you! 💯
