### ISSUE TITLE
Range picker ver1.4.0 Single Day Selection issue

### ISSUE THREAD

**Issue by manish7i** [PredixDev/px-rangepicker#39]
We are using the date range picker version 1.4.0 from https://github.com/PredixDev/px-rangepicker.git#^1.4.0
 
And we are seeing some bugs while selecting the dates as described below. We were not seeing this issues in the previous version 1.3.8
 
 
1. Selecting just 1 day is hard and doesn’t select it properly. 
![screen shot 2017-06-29 at 11 38 25 am](https://user-images.githubusercontent.com/1343298/27705359-765d59d4-5cc2-11e7-8537-f14aaeaac92b.png)

2. If I manage to select just 1 day then the date goes back to previous day.
![screen shot 2017-06-29 at 11 44 12 am](https://user-images.githubusercontent.com/1343298/27705361-79164898-5cc2-11e7-838a-6f644550dd10.png)

**Comment by Menkhaus-ge** [comment]
I'm currently looking into this issue.

**Comment by Menkhaus-ge** [comment]
What timezone are you setting your rangepicker to?

**Comment by manish7i** [comment]
UTC.

This is how I am setting range in the code.
 
var formattedEndDate = moment().utc().format("YYYY-MM-DD");
var formattedStartDate = moment().subtract(10, "days").utc().format("YYYY-MM-DD");

$scope.range = {
      from: formattedStartDate,
      to: formattedEndDate
};

**Comment by manish7i** [comment]
Earlier it was as below, but still, doesn't work. I remember in the old version (1.3.8), I fixed it by removing the Time from the Date, so I tried it here as well.

var formattedEndDate = moment().utc().format();
var formattedStartDate = moment().subtract(10, "days").utc().format();

$scope.range = {
from: formattedStartDate,
to: formattedEndDate
};

**Comment by manish7i** [comment]
My HTML is like this 

<px-rangepicker
        id="rangepicker" range="{{range}}" date-format="YYYY/MM/DD"
        show-buttons="true" hide-time="true" hide-presets="true"
        block-future-dates="true" time-zone="UTC">
      </px-rangepicker>

**Comment by manish7i** [comment]
My HTML is as below

<px-rangepicker
        id="rangepicker" range="{{range}}" date-format="YYYY/MM/DD"
        show-buttons="true" hide-time="true" hide-presets="true"
        block-future-dates="true" time-zone="UTC">
      </px-rangepicker>

**Comment by manish7i** [comment]
HTML is as below
`<px-rangepicker
        id="rangepicker" range="{{range}}" date-format="YYYY/MM/DD"
        show-buttons="true" hide-time="true" hide-presets="true"
        block-future-dates="true" time-zone="UTC">
      </px-rangepicker>`

**Comment by manish7i** [comment]
Hey Kate,

I think I got the issue. from: formattedStartDate, to: formattedEndDate has to be in string. Will get back in some time.

**Comment by Menkhaus-ge** [comment]
I'm an still working on why selected a day goes to the previous day. 

If you try to pick one day when the times are the same, you will get an error. We do not allow the range.from and range.to to be the same (ex. range='{"from":"2017-06-13T01:00:00.000Z","to":"2017-06-13T01:00:00.000Z"}') because it is then not a range but a single moment in time. Depending on your use case you may want to use the px-datetime-picker.

**Comment by Menkhaus-ge** [comment]
You can remove the .utc().format() from you variables because they are being defined by `time-zone` and `date-format`
This doesn't fix the issue but the the way we recommend setting those variables would be 
```
formattedEndDate = Px.moment().toISOString();
formattedStartDate = Px.moment().subtract(10, "days").toISOString();
```
We use Px.moment() to keep our version on moment() synced throughout all of our components.

**Comment by manish7i** [comment]
Thanks Kate...We need to show 1 Day in the Date picker and need to fetch data for hours.
However, still i am not able to do it.

Here is the code
`<px-rangepicker hide-time="true" hide-presets="true" show-buttons="true" block-future-dates="true"
                      date-format="YYYY/MM/DD"
                      range='{{range}}'>
      </px-rangepicker>`

`var formattedEndDate = Px.moment().toISOString();
    var formattedStartDate = Px.moment().subtract(10, "days").toISOString();

    // $scope.range = {"from":"2016-01-01T00:00:00.000Z","to":"2016-07-01T00:00:00.000Z"}
    $scope.range = '{"from":"' + formattedStartDate + '","to":"' + formattedEndDate + '"}';`

**Comment by manish7i** [comment]
BTW, the order of the attributes in the directive matters too - 

Doesn't work:
`<px-rangepicker
          id="rangepicker" range="{{range}}" date-format="MM/DD/YYYY" time-format="hh:mm:ss A"
          show-buttons="true" hide-time="true" hide-presets="true"
          block-future-dates="true">
        </px-rangepicker>`

Works:
`<px-rangepicker
          id="rangepicker" hide-time="true" show-buttons="true"  date-format="MM/DD/YYYY" time-format="HH:mm:ss" time-zone="UTC"
          hide-presets="true"
          block-future-dates="true" range="{{range}}">
        </px-rangepicker>`

**Comment by Menkhaus-ge** [comment]
We had some timezone issues that were causing the date to select the previous day. 
We have pushed a fix for this in: 
```
px-datetime-common commit 8e83660
px-calendar-picker commit 43e371a
px-datetime-picker commit ac8a1a7
```
