### ISSUE TITLE
Rangepicker calendar modal laid behind other element

### ISSUE THREAD

**Issue by iamcap** [PredixDev/px-rangepicker#4]
![screen shot 2016-03-01 at 10 49 09 am](https://cloud.githubusercontent.com/assets/3128338/13437879/4c231b18-df9b-11e5-9997-190042658200.png)

**Comment by iamcap** [comment]
After upgrade px-rangepicker, we encounter this issue. 

Does px-rangepicker always require a parent element with "position: relative;" ?

**Comment by ClaudiaHu1** [comment]
![screen shot 2016-03-01 at 4 26 04 pm](https://cloud.githubusercontent.com/assets/15002900/13446685/5d76c5de-dfca-11e5-8567-9ca2e711b7a5.png)
After change the parent element with "position: relative", it looks like this.

**Comment by mdwragg** [comment]
Solved for customer.
