### ISSUE TITLE
More presets in the Range Picker

### ISSUE THREAD

**Issue by manish7i** [PredixDev/px-rangepicker#41]
Hi,

We are working on a Schindler use case where they want to pick a date range for a complete year. 
Is there a way we can add or enable presets for Quarters, 6 months and 1 year?

<img width="580" alt="screen shot 2017-07-24 at 1 47 59 pm" src="https://user-images.githubusercontent.com/1343298/28544335-9fccde8e-7077-11e7-8696-919cc9b1d682.png">

**Comment by benoitjchevalier** [comment]
Presets are configurable through `presetRanges` as seen on the [API](https://www.predix-ui.com/#/components/px-rangepicker/)
