### ISSUE TITLE
Light/Dark Theme problem

### ISSUE THREAD

**Issue by vikramaroskar** [PredixDev/px-rangepicker#47]
Hello.

On the demo page, there are 2 theme supported. lightTheme and darkTheme.

The same can be set on px-rangefield via  --px-datetime-range-field-to-color 
and on 
px-datetime-range-panel via --px-range-panel-background-color and other styling properties.

Is there a way, we can set styling on px-rangepicker as well directly. Currently, the documentation states nothing on it, and asks to refer to child components.

I tried 
<style is="custom-style">
        px-rangepicker {

        px-rangepicker.px-range-panel {
          --px-range-panel-background-color: "ff0000";
          --px-range-panel-z-index: 1000;
        }

        --px-datetime-range-field-to-color:"ff0000";
        }
      </style>

but this doesn't work.
Can someone help..

**Comment by randyaskin** [comment]
First, you can't nest CSS selectors without sass/less/etc. Second, color values are not quoted. Third, you don't need to nest, just scope the variables to the rangepicker and the sub-components will pick them up automatically, e.g.
```
<style is="custom-style">
  px-rangepicker {
    --px-range-panel-background-color: #ff0000;
    --px-range-panel-z-index: 1000;
  }
</style>
```

**Comment by vikramaroskar** [comment]
Thanks @randyaskin.

This works.
