### ISSUE TITLE
Alignment of range-panel in range picker.

### ISSUE THREAD

**Issue by vikramaroskar** [PredixDev/px-rangepicker#48]
The range panel popping up is always left aligned with the range field.
In my app, the rangepicker is on the right side, and clicking and opening up the panel, causes a problem, wherein the panel is shown outside the normal view screen..

![image](https://user-images.githubusercontent.com/19361170/30165858-3166fcb2-93ff-11e7-82b4-23932327f31d.png)

Is there a way, by which this alignment can be controlled. would help a lot. Thanks.

**Comment by Menkhaus-ge** [comment]
This is a know issue. It is not a trivial fix and currently we do not have bandwidth to fix it. 
Our initial thought is use `iron-dropdown` to position the panel. We have done this in other components.

**Comment by vikramaroskar** [comment]
Thanks @Menkhaus-ge

**Comment by katemenkhaus** [comment]
This as been fixed in v3.2.2
