### ISSUE TITLE
Provided range changes depending on provided timeFormat

### ISSUE THREAD

**Issue by jschlieber** [PredixDev/px-rangepicker#50]
## Expected behavior and actual behavior:
The provided date range should not be changed by the component internals. The provided `dateFormat` and `timeFormat` should only be used to format the provided dates and **not mutate** them!

## Steps to reproduce the problem:
Provide a date range with seconds and/or milliseconds not equal to zero. Also Provide a `timeFormat` like `HH:mm`. The date range will be mutated and a `px-datetime-range-submitted` event will be fired with a changed date range where seconds and milliseconds will be set to zero.

## Environment:
component version number: 2.1.1

**Comment by randyaskin** [comment]
I don't believe this is still happening in the latest implementation of datetime.

**Comment by katemenkhaus** [comment]
Cannot reproduce in the latest version of the rangepicker. Please reopen if you are still having this issue.
