### ISSUE TITLE
Setting new Date Range change and apply it does not reset the previous selected Preset 

### ISSUE THREAD

**Issue by priyabrat1801** [PredixDev/px-rangepicker#51]
If we select a preset and apply, the date fields show the updated date. Now if the range is changed manually, the date changes on the field but the previously selected preset still remains.
<img width="471" alt="screen shot 2017-11-09 at 11 37 16 am" src="https://user-images.githubusercontent.com/7915828/32625890-6ed76aea-c542-11e7-9479-bf6d9536479b.png">

**Comment by randyaskin** [comment]
No longer true in latest version of px-rangepicker. As soon as a date is manually selected, the highlight fades from the previously selected Preset.
