### ISSUE TITLE
Responsive behavior does not show full rangepicker in narrow view

### ISSUE THREAD

**Issue by sgoodrow** [PredixDev/px-rangepicker#52]
## Expected behavior and actual behavior:
When using a narrow browser, the rangepicker should responsively update so that the full component is visible, instead of being clipped by the viewport.

## Steps to reproduce the problem:
1) Add rangepicker to page.
2) Shrink window width to less than full rangepicker width.
3) Observing clipping of rangepicker "to" field.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
1) Version Number: 2.1.2
2) Browser: Chrome 62.0l.3202.94
3) OSX10.11.6

## Screenshots (_optional, but very helpful_):
![rangepickerbug](https://user-images.githubusercontent.com/5815812/33953993-cd7a19da-dfeb-11e7-9286-fe878fb62bc7.png)

**Comment by katemenkhaus** [comment]
There are a few options for this. 
- You can set add the`allowWrap` property and the fields will stack when the screen is too small. 
- You can set add the`hideIcon` property to hide all the icons
- You can shorten your `dateFormat` and `timeFormat`
