### ISSUE TITLE
Error state can be retained after initial trigger with no way to clear it out.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-rangepicker#54]
## Expected behavior and actual behavior:
In certain conditions, the error state lingers even after fixing the range.

## Steps to reproduce the problem:
1. Without opening the calendar panel, enter an invalid month in the rangepicker,e.g. set mm to 13. Note, the proper error is triggered.
2. Open the panel and select a preset, the preset seems to correctly be selected (highlights on the calendar) and also changed in the range field. But note the error message and red highlights remain in the range field even though the new range is valid.
3.  Now select Apply.
4.  The error message and red highlights remain in the range field and the range is set back to empty or the original range, not the selected range in step 2.  

Screenshots below.

## Environment :
Rangepicker: v3.0.0
Browsers: All supported

### **Triggering the error:**
![screen shot 2017-12-21 at 10 10 10 am](https://user-images.githubusercontent.com/10835611/34269347-c7f6011a-e638-11e7-91d5-56f0290a88cb.png)

### **Selecting a Preset:**
![screen shot 2017-12-21 at 10 10 26 am](https://user-images.githubusercontent.com/10835611/34269368-dc01385a-e638-11e7-8d75-51a56b986315.png)

### **Resulting range after selecting Apply:**
![screen shot 2017-12-21 at 10 28 58 am](https://user-images.githubusercontent.com/10835611/34269593-ccec9b2e-e639-11e7-8617-98763ebca39f.png)

## Code example:
This is reproducible with the simple_demo.html sample code.

**Comment by katemenkhaus** [comment]
fixed in v3.3.1
