### ISSUE TITLE
fromMoment is nulled out unexpectedly from inside px-rangepicker

### ISSUE THREAD

**Issue by davidrleonard** [PredixDev/px-rangepicker#59]
When the `fromMoment` object is set early by an app, a bunch of property effects can happen that eventually set it to null. This clears out the app's value for `fromMoment` and the rangepicker is rendered with a blank from field. The `toMoment` object doesn't appear to suffer from the same problem.

This appears to happen at some point when we copy `fromMoment` -> `_tempFromMomentObj` and later try to copy `_tempFromMomentObj` -> `fromMoment`. I can't pinpoint the exact method that does this, but the bug seems to kick in here:

https://github.com/PredixDev/px-datetime-common/blob/master/px-datetime-range-behavior.html#L175

After a valid `fromMoment` is passed in and a bunch of stuff happens, at some point the `_tempFromMomentObj` is nulled out and then `fromMoment` is set to that null value.

See #58 which reported this underlying bug. Demo of the bug is here: https://codesandbox.io/s/1ow02wvv64

1. Click "lazy render pickers" button
2. The from moment is empty for the new rangepicker. This app's process exposes the timing bug. It is unrelated to the lazy loading issue.

cc @katemenkhaus @benoitjchevalier

**Comment by katemenkhaus** [comment]
This has been fix with v3.1.1 of the rangepicker
