### ISSUE TITLE
Possible redundant Import

### ISSUE THREAD

**Issue by barkerb1** [PredixDev/px-rangepicker#6]
moment.js is called in both px-calendar.html and px-calendar-cell.html.  This is causing issues loading a page as HTTPS (Interestingly it doesn't cause an issue over HTTP) where the page hangs at the second import.

I commented out the line <script src="../moment/moment.js"></script> in px-calendar-cell.html and it fixed the issue for my case.  I'm not sure if this is a systemic issue, but it may be worth exploring.

Thanks,
Brad

**Comment by nonmetalhail** [comment]
Hi Brad,

I am not seeing it hang on our demo page with https:
https://pxc-demos.grc-apps.svc.ice.ge.com/bower_components/px-rangepicker/demo.html

What browser are you using and under what conditions do you see this issue? Do you see it on our demo page?

**Comment by mdwragg** [comment]
@nonmetalhail edited it to be the external demo page ;-)

**Comment by nonmetalhail** [comment]
Assuming this is solved; please reopen if it is still an issue.
