### ISSUE TITLE
Cannot see Apply button sometimes

### ISSUE THREAD

**Issue by galvatron7** [PredixDev/px-rangepicker#60]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:
Expected behavior: see "Apply" button on date range picker always.
Actual behavior: On Windows machines on Chrome, it does not always show the "Apply" button. The workaround is to try to scroll inside the component to the bottom, or change the zoom settings on the Window.

## Steps to reproduce the problem:
1. Open date range picker in Chrome on Windows machine
2. Observe that the component is cut off and does not show the "Apply" button

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-rangepicker version 1.3.7
Browser: Chrome
OS: Windows

## Screenshots (_optional, but very helpful_):

![image](https://user-images.githubusercontent.com/11971781/35527023-34a35f7e-04de-11e8-9fca-1439f0eeb28b.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by katemenkhaus** [comment]
This has been fixed in v3.2.2. The panel will now position itself in whatever space it has in the window. If the panel is in a smaller space than it is wide or tall, it will become scrollable. 

Also if so needed we've added the ability in v3.3.0 to allow scrolling on the page when the panel is open. When the `scrollAction` property is set to `refit`, the panel will refit itself on the page when the user scrolls.
