### ISSUE TITLE
Right side date field is updated on selecting a date by clicking on left side calendar icon

### ISSUE THREAD

**Issue by shrau94** [PredixDev/px-rangepicker#61]
# Right side date field is updated on selecting a date by clicking on left side calendar icon

Hi,

I came across the following scenario for the px-rangepicker. Kindly go through the details and let me know regarding this behavior.

## Expected behavior and actual behavior:
Actual behavior: The date on the right side date-time-entry-cell is updated.
Expected behavior: The date on the left side date-time-entry-cell should be updated.
(Refer Screenshots)

## Steps to reproduce the problem:
1. Open the px-rangepicker by selecting on the "from" (the one on the left date-time-entry-cell) calendar icon.
2. In the opened calender select a date from the right side calender that opens.
3. The "to" field gets populated for the date.

## Environment:
component version: 3.1.0

## Screenshots:
![capture1](https://user-images.githubusercontent.com/10210384/35549156-28d31b5e-05aa-11e8-8c84-2f6c1cc69249.JPG)

![capture2](https://user-images.githubusercontent.com/10210384/35549159-2b6ef82e-05aa-11e8-8e4c-cd74dc2f80b6.JPG)

**Comment by benoitjchevalier** [comment]
Opening the panel from the 'from' or 'to' calendar icon actually drives the same behavior. In both cases it opens the panel, which then tries to guess what choices you are currently making. 

We do not allow to change only one of the two (from or to) dates by only clicking, opening the panel means changing the whole range by re-choosing both a "from" and "to" date. On the first click we make a guess at which date you have just selected. The guess is that by clicking the right calendar you are "more likely" to have chosen a "to" date than a "from" date. 

Once the second date is selected the rangepicker will appropriately swap the two dates if the guess was wrong.
