### ISSUE TITLE
px-datetime-range-submitted event is fired multiple times when the range value is getting updated in the controller

### ISSUE THREAD

**Issue by linduatge** [PredixDev/px-rangepicker#63]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

Expected behaviour: The px-datetime-range-submitted event should be fired only once.
Actual behaviour: The px-datetime-range-submitted event is getting fired multiple times.

## Steps to reproduce the problem:
1) Specify a px-rangepicker in a html file and assign the range attribute to a scope variable.
2) Add a icon or button in the html which on click will trigger a function to update the scope variable.
3) In the angular controller define the initial value for this scope variable.
4) In the angular controller, in the click function update the scope variable to a new value.
5) Now click the icon/button, the range gets updated with the new value, and the px-datetime-range-submitted event is fired multiple times.
6) This issue does not happen if we update the range by opening the panel and clicking the Apply button or manually editing the date/time in the rangepicker. At that time only once the event is fired.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

px-rangepicker version 1.3.7
Browser: Any
OS: Any

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

**Comment by randyaskin** [comment]
Version 1.3.7 of rangepicker is nearly a year old. I don't really follow your Angular-related issues, but redundant firing of the change event was one of many reasons we re-wrote version 3 of the rangepicker (and new versions of [all of the datetime components](https://www.predix-ui.com/#/develop/datetime-changeshttps://www.predix-ui.com/#/develop/datetime-changes)) to remove the problematic syncing between Moment objects and ISO strings. I recommend updating to a later version if possible, as we no longer support or make updates to v1 of this component.
