### ISSUE TITLE
Issue in setting default date and time (also present in demo page)

### ISSUE THREAD

**Issue by shrau94** [PredixDev/px-rangepicker#64]
Hi,

After I ran the simple_demo.html from the demo folder in px-rangepicker. The following scenario was discovered. I have used a similar way in my code for setting default date and time to the px-rangepicker as done in the demo page and the same problem is reproducing there as well.
Please provide a way to set default dates and times explicitly.

## Expected behavior and actual behavior

**Actual:** After clicking on the left side arrow icon in calendar the date from the previous month is selected.
**Expected:** After clicking on the left side arrow icon in calendar the date range selected should not change.
(refer screenshots)

## Steps to reproduce the problem

1. Click on the left side calendar icon.
2. On the left calendar panel click on the previous icon to select previous month.
**Problem persists in additional step:**
3. Click on cancel button and repeat the above two steps.

## Environment 
component version number 3.2.0

## Screenshots

![capture5](https://user-images.githubusercontent.com/10210384/35672053-510bdc9a-0763-11e8-8546-97f2f1871f30.JPG)

![capture6](https://user-images.githubusercontent.com/10210384/35672055-5363532e-0763-11e8-9bb6-e0dad40e229e.JPG)

**Comment by randyaskin** [comment]
Possible duplicate or at least related to: https://github.com/PredixDev/px-datetime-picker/issues/14

**Comment by shrau94** [comment]
When can we expect a fix for this?

**Comment by katemenkhaus** [comment]
Currently looking into it. I do not have a time estimate for you yet.

**Comment by katemenkhaus** [comment]
This has been fix in v2.0.8 of px-calendar-picker

**Comment by shrau94** [comment]
@katemenkhaus Thanks!
