### ISSUE TITLE
Panel not updated when date manually changed from the field. from and to moment are also not modified

### ISSUE THREAD

**Issue by shrau94** [PredixDev/px-rangepicker#65]
Hi,

In my code I have a form in which if the date range is invalid then the form should not be submitted. When the date is updated from the from or to field and the date is before the min date or is greater than the to date or from is greater than to date then error messages are shown below the field. But when the panel is open then the date that were previously selected are highlighted. Also the isValid property still says true and from and to moment are not modified.
(refer screenshots)

## Expected behavior and actual behavior:
Expected: The highlighted date is the calendar should be updated. The isValid property should change accordingly.

## Steps to reproduce the problem:
1. Open the calendar panel and select the from date as 1/1/2018 and to date as 5/1/2018.
2. Manually change the from date in the field to 10/1/2018.
3. Manually change the to date in the field to 9/1/2018.
4. Error message is visible below.
5. Open the calendar panel, previously selected dates are highlighted.

## Environment:
component version: 3.2.0

## Screenshots:
![capture7](https://user-images.githubusercontent.com/10210384/35727114-0ae357f0-082d-11e8-97b9-c715b0ea6bee.JPG)

![capture8](https://user-images.githubusercontent.com/10210384/35727128-14d7aa68-082d-11e8-887f-9b098eef2e9b.JPG)

![capture9](https://user-images.githubusercontent.com/10210384/35727135-191ec638-082d-11e8-9f8e-373d0ecef20f.JPG)

![capture10](https://user-images.githubusercontent.com/10210384/35727391-f745de4c-082d-11e8-9812-093c4fc4502b.JPG)

**Can you provide the property which is set or the even that is fired that can be used in order to determine whether the dates selected are valid or not so that I can use that in the form.**
Thanks a lot!

**Comment by katemenkhaus** [comment]
The `isValid` property on rangepicker should be `false` when the fields are invalid. I will push a fix. 

However the `Expected: The highlighted date is the calendar should be updated.` What do you expect the calendar to update to?

**Comment by shrau94** [comment]
I would suggest the dates in the panel to be deselected so that no date is highlighted when the calendar is open. Because at this state the field and panel are contrary to each other.  

`The isValid property on rangepicker should be false when the fields are invalid. I will push a fix.` 
Thank you so much! :)

**Comment by shrau94** [comment]
When can we expect a fix for this?

**Comment by katemenkhaus** [comment]
Its in progress, will have a fix in a day or two.

**Comment by katemenkhaus** [comment]
v3.3.1 fixed the `isValid` property issue. When the fields are invalid it is now reflected to the rangepicker `isValid` property.

**Comment by katemenkhaus** [comment]
![screen shot 2018-02-12 at 9 14 21 am](https://user-images.githubusercontent.com/14931112/36109714-1924f65c-0fd5-11e8-8c53-988473b5eb1a.png)
When the field is invalid the calendar selection will gray out. 

This was implemented in v3.3.2 and v3.3.3

**Comment by shrau94** [comment]
@katemenkhaus Thanks! This solved my issue.

**Comment by shrau94** [comment]
Thanks! Works perfectly :)

**Comment by shrau94** [comment]
The `is-valid-changed` event which is mentioned in the demo page is not fired when the `isValid` property is changed. We need that event to unset the custom error messages that we are setting when `isValid` is `false` i.e. when error message is set by rangepicker we need to unset our custom messages.
Can you add the `is-valid-changed` event?

**Comment by katemenkhaus** [comment]
I'm not sure why your not able to capture the event. I loaded up the simple demo, added an event listener `$0.addEventListener('is-valid-changed', function(e){console.log(e.detail.value);})` to the `px-rangepicker` tag, and when the validation changed value it printed out in the console as expected. 

When a property that has notify set to true changes value then an event `property-changed` is fired. See documentation for polymer 1 & 2 below. 
https://www.polymer-project.org/1.0/docs/devguide/properties#notify
https://www.polymer-project.org/2.0/docs/devguide/data-system#change-events
