### ISSUE TITLE
change time only in text box is not consistent when click cancel

### ISSUE THREAD

**Issue by iamcap** [PredixDev/px-rangepicker#8]
To reproduce

http://jsfiddle.net/iamcap/3xyr6ppz/10/

1) open rangepicker modal
2) update to-time and click apply
3) open again rangepicker modal
4) click cancel

**Comment by mdwragg** [comment]
Thanks @iamcap. Can you take a look when you have a min @nonmetalhail? Thanks.

**Comment by nonmetalhail** [comment]
Ok, I just pushed a fix to master with tag v0.2.1. Thanks.
